/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

fn main() {
    carbide_version::build();

    // generated by `sqlx migrate build-script`
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
}
