{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: machine-a-tron-certificate
  namespace: {{ include "machine-a-tron.namespace" . }}
spec:
  duration: {{ .Values.global.certificate.duration }}
  renewBefore: {{ .Values.global.certificate.renewBefore }}
  secretName: {{ .Values.certificate.secretName }}
  privateKey:
    algorithm: {{ .Values.global.certificate.privateKey.algorithm }}
    size: {{ .Values.global.certificate.privateKey.size }}
  issuerRef:
    kind: {{ .Values.global.certificate.issuerRef.kind }}
    name: {{ .Values.global.certificate.issuerRef.name }}
    group: {{ .Values.global.certificate.issuerRef.group }}
  dnsNames:
{{- range .Values.certificate.serviceDnsNames }}
    - {{ . | quote }}
{{- end }}
  uris:
{{- range .Values.certificate.uris }}
    - {{ . | quote }}
{{- end }}
{{- end }}
