apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "machine-a-tron.namespace" . }}
  labels:
    app: {{ include "machine-a-tron.name" . }}
spec:
  selector:
    app: {{ include "machine-a-tron.name" . }}
  ports:
    - name: redfish
      port: {{ .Values.service.redfishPort }}
      targetPort: redfish
      protocol: TCP
    - name: ssh
      port: {{ .Values.service.sshPort }}
      targetPort: {{ .Values.service.sshTargetPort }}
      protocol: TCP
