apiVersion: v1
kind: Service
metadata:
  name: carbide-ntp
  namespace: {{ include "carbide-ntp.namespace" . }}
  labels:
    {{- include "carbide-ntp.labels" . | nindent 4 }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "carbide-ntp.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
