namespaceOverride: ""

image:
  repository: machine-a-tron
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []

global:
  certificate:
    duration: 720h0m0s
    renewBefore: 360h0m0s
    privateKey:
      algorithm: ECDSA
      size: 384
    issuerRef:
      kind: ClusterIssuer
      name: vault-forge-issuer
      group: cert-manager.io

serviceAccount:
  create: true
  name: machine-a-tron

certificate:
  enabled: true
  secretName: machine-a-tron-certificate
  serviceDnsNames: []
  uris: []

service:
  name: machine-a-tron-bmc-mock
  redfishPort: 1266
  sshPort: 22
  sshTargetPort: 2222

config:
  mountPath: /opt/machine-a-tron/config/mat.toml
  contents: ""

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
