# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide
WORKDIR ./carbide

RUN mkdir -p /opt/carbide/pxe/templates
RUN mkdir -p /forge-boot-artifacts/blobs

COPY .skaffold/target/carbide-pxe/debug/carbide /opt/carbide/
COPY pxe/templates/* /opt/carbide/pxe/templates/
COPY pxe/static/* /forge-boot-artifacts/blobs/
