# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide
WORKDIR ./carbide
COPY .skaffold/target/carbide-bmc-proxy/debug/carbide-bmc-proxy /opt/carbide/
