# syntax=docker/dockerfile:1.4

#
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

FROM debian:bookworm-slim AS carbide

RUN --mount=type=cache,target=/var/cache/apt apt-get update && apt-get install -y --no-install-recommends \
  bash \
  ca-certificates \
  python3-minimal \
  tini \
  unbound && \
  rm -rf /var/lib/apt/lists/*

COPY dev/deployment/localdev/start-unbound.localdev.sh /usr/local/bin/start-unbound.sh
COPY dev/deployment/localdev/unbound-exporter.localdev.py /usr/local/bin/unbound-exporter.localdev

RUN chmod +x /usr/local/bin/start-unbound.sh && \
  chmod +x /usr/local/bin/unbound-exporter.localdev && \
  mkdir -p /etc/unbound/local.conf.d /etc/unbound/keys && \
  chown -R unbound:unbound /etc/unbound

EXPOSE 53/tcp 53/udp 8953/tcp 9167/tcp

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/start-unbound.sh"]
