# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide

WORKDIR /opt/carbide
COPY .skaffold/target/carbide-admin-cli/debug/carbide-admin-cli /opt/carbide/
RUN ln -s /opt/carbide/carbide-admin-cli /opt/carbide/forge-admin-cli

ENV PATH="/opt/carbide:${PATH}"
