# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide

WORKDIR ./carbide
COPY .skaffold/target/carbide-api/debug/carbide-api /opt/carbide/
COPY .skaffold/target/carbide-admin-cli/debug/carbide-admin-cli /opt/carbide/
RUN ln -s /opt/carbide/carbide-admin-cli /opt/carbide/forge-admin-cli
COPY crates/api/casbin-policy.csv /opt/carbide/
COPY pxe/static/blobs/internal/aarch64/secure-boot-pk.pem /forge-boot-artifacts/blobs/internal/aarch64/secure-boot-pk.pem
ENV CASBIN_POLICY_FILE=/opt/carbide/casbin-policy.csv
