# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide
WORKDIR ./carbide

RUN mkdir -p /forge-boot-artifacts/blobs

COPY pxe/static/* /forge-boot-artifacts/blobs/
