# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM registry.minikube/runtime-container:latest as carbide
WORKDIR ./carbide
COPY .skaffold/target/carbide-dns/debug/carbide-dns /opt/carbide/
