# syntax=docker/dockerfile:1.4

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide
WORKDIR ./carbide

RUN mkdir -p /var/log/consoles

COPY .skaffold/target/carbide-ssh-console/debug/ssh-console /opt/carbide/
