# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

FROM runtime-container-localdev:latest as carbide


WORKDIR /
COPY crates/machine-validation/config /machine-validation/config

CMD exec /bin/sh -c "trap : TERM INT; sleep 9999999999d & wait"
