// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuthIssuerCreateOrUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthIssuerCreateOrUpdateRequest{}

// AuthIssuerCreateOrUpdateRequest Complete representation used to create or replace an external JWT Auth Issuer.  `issuerUrl` selects the resource. Repeating the same body is idempotent; changing any other field fully replaces the stored operator configuration. Omitted optional arrays are stored as empty arrays.  `origin` is ignored — API-managed issuers always receive `origin: custom`. Only static claim mappings (`orgName` + optional `roles`) are accepted.
type AuthIssuerCreateOrUpdateRequest struct {
	// Expected JWT `iss` claim / OIDC issuer URL and natural upsert key.
	IssuerUrl string `json:"issuerUrl"`
	// JWKS URL. Defaults to `{issuerUrl}/.well-known/jwks.json` when omitted.
	JwksUrl *string `json:"jwksUrl,omitempty"`
	// JWKS fetch timeout (Go duration string). Defaults to `\"5s\"`.
	JwksTimeout *string `json:"jwksTimeout,omitempty"`
	// Enables client-credentials flow (disconnected mode only).
	ServiceAccount *bool `json:"serviceAccount,omitempty"`
	// Issuer-level allowed audience set.
	Audiences []string `json:"audiences,omitempty"`
	// Issuer-level required scope set.
	Scopes []string `json:"scopes,omitempty"`
	// Org/role mapping entries. Dynamic attribute fields are rejected with `400`.
	ClaimMappings []AuthIssuerClaimMapping `json:"claimMappings,omitempty"`
}

type _AuthIssuerCreateOrUpdateRequest AuthIssuerCreateOrUpdateRequest

// NewAuthIssuerCreateOrUpdateRequest instantiates a new AuthIssuerCreateOrUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthIssuerCreateOrUpdateRequest(issuerUrl string) *AuthIssuerCreateOrUpdateRequest {
	this := AuthIssuerCreateOrUpdateRequest{}
	this.IssuerUrl = issuerUrl
	return &this
}

// NewAuthIssuerCreateOrUpdateRequestWithDefaults instantiates a new AuthIssuerCreateOrUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthIssuerCreateOrUpdateRequestWithDefaults() *AuthIssuerCreateOrUpdateRequest {
	this := AuthIssuerCreateOrUpdateRequest{}
	return &this
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *AuthIssuerCreateOrUpdateRequest) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *AuthIssuerCreateOrUpdateRequest) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

// GetJwksUrl returns the JwksUrl field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetJwksUrl() string {
	if o == nil || IsNil(o.JwksUrl) {
		var ret string
		return ret
	}
	return *o.JwksUrl
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetJwksUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUrl) {
		return nil, false
	}
	return o.JwksUrl, true
}

// HasJwksUrl returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasJwksUrl() bool {
	if o != nil && !IsNil(o.JwksUrl) {
		return true
	}

	return false
}

// SetJwksUrl gets a reference to the given string and assigns it to the JwksUrl field.
func (o *AuthIssuerCreateOrUpdateRequest) SetJwksUrl(v string) {
	o.JwksUrl = &v
}

// GetJwksTimeout returns the JwksTimeout field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetJwksTimeout() string {
	if o == nil || IsNil(o.JwksTimeout) {
		var ret string
		return ret
	}
	return *o.JwksTimeout
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetJwksTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.JwksTimeout) {
		return nil, false
	}
	return o.JwksTimeout, true
}

// HasJwksTimeout returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasJwksTimeout() bool {
	if o != nil && !IsNil(o.JwksTimeout) {
		return true
	}

	return false
}

// SetJwksTimeout gets a reference to the given string and assigns it to the JwksTimeout field.
func (o *AuthIssuerCreateOrUpdateRequest) SetJwksTimeout(v string) {
	o.JwksTimeout = &v
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetServiceAccount() bool {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret bool
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given bool and assigns it to the ServiceAccount field.
func (o *AuthIssuerCreateOrUpdateRequest) SetServiceAccount(v bool) {
	o.ServiceAccount = &v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *AuthIssuerCreateOrUpdateRequest) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *AuthIssuerCreateOrUpdateRequest) SetScopes(v []string) {
	o.Scopes = v
}

// GetClaimMappings returns the ClaimMappings field value if set, zero value otherwise.
func (o *AuthIssuerCreateOrUpdateRequest) GetClaimMappings() []AuthIssuerClaimMapping {
	if o == nil || IsNil(o.ClaimMappings) {
		var ret []AuthIssuerClaimMapping
		return ret
	}
	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerCreateOrUpdateRequest) GetClaimMappingsOk() ([]AuthIssuerClaimMapping, bool) {
	if o == nil || IsNil(o.ClaimMappings) {
		return nil, false
	}
	return o.ClaimMappings, true
}

// HasClaimMappings returns a boolean if a field has been set.
func (o *AuthIssuerCreateOrUpdateRequest) HasClaimMappings() bool {
	if o != nil && !IsNil(o.ClaimMappings) {
		return true
	}

	return false
}

// SetClaimMappings gets a reference to the given []AuthIssuerClaimMapping and assigns it to the ClaimMappings field.
func (o *AuthIssuerCreateOrUpdateRequest) SetClaimMappings(v []AuthIssuerClaimMapping) {
	o.ClaimMappings = v
}

func (o AuthIssuerCreateOrUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthIssuerCreateOrUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["issuerUrl"] = o.IssuerUrl
	if !IsNil(o.JwksUrl) {
		toSerialize["jwksUrl"] = o.JwksUrl
	}
	if !IsNil(o.JwksTimeout) {
		toSerialize["jwksTimeout"] = o.JwksTimeout
	}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.ClaimMappings) {
		toSerialize["claimMappings"] = o.ClaimMappings
	}
	return toSerialize, nil
}

func (o *AuthIssuerCreateOrUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"issuerUrl",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthIssuerCreateOrUpdateRequest := _AuthIssuerCreateOrUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthIssuerCreateOrUpdateRequest)

	if err != nil {
		return err
	}

	*o = AuthIssuerCreateOrUpdateRequest(varAuthIssuerCreateOrUpdateRequest)

	return err
}

type NullableAuthIssuerCreateOrUpdateRequest struct {
	value *AuthIssuerCreateOrUpdateRequest
	isSet bool
}

func (v NullableAuthIssuerCreateOrUpdateRequest) Get() *AuthIssuerCreateOrUpdateRequest {
	return v.value
}

func (v *NullableAuthIssuerCreateOrUpdateRequest) Set(val *AuthIssuerCreateOrUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthIssuerCreateOrUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthIssuerCreateOrUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthIssuerCreateOrUpdateRequest(val *AuthIssuerCreateOrUpdateRequest) *NullableAuthIssuerCreateOrUpdateRequest {
	return &NullableAuthIssuerCreateOrUpdateRequest{value: val, isSet: true}
}

func (v NullableAuthIssuerCreateOrUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthIssuerCreateOrUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
