// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
	"time"
)

// checks if the Issuer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Issuer{}

// Issuer A runtime-managed external JWT issuer registered via the Provider Admin API.
type Issuer struct {
	// Unique identifier of the issuer.
	Id *string `json:"id,omitempty"`
	// Token processor. Always `custom` for API-created issuers.
	Origin *string `json:"origin,omitempty"`
	// Expected JWT `iss` claim / OIDC issuer URL. Immutable after creation.
	IssuerUrl *string `json:"issuerUrl,omitempty"`
	// URL from which signing keys are fetched. Defaults to `{issuerUrl}/.well-known/jwks.json`.
	JwksUrl *string `json:"jwksUrl,omitempty"`
	// JWKS fetch timeout (Go duration string, e.g. `\"5s\"`).
	JwksTimeout *string `json:"jwksTimeout,omitempty"`
	// Enables client-credentials flow (disconnected mode only).
	ServiceAccount *bool `json:"serviceAccount,omitempty"`
	// Issuer-level allowed audience set; the token must carry at least one.
	Audiences []string `json:"audiences,omitempty"`
	// Issuer-level required scope set; the token must carry all.
	Scopes []string `json:"scopes,omitempty"`
	// Org/role mapping entries. Only static mappings (`orgName`) are permitted via the API.
	ClaimMappings []IssuerClaimMapping `json:"claimMappings,omitempty"`
	// Whether signing keys have been fetched from `jwksUrl`. Registration never contacts the identity provider, so an issuer starts `Pending` and becomes `Ready` once a background fetch succeeds. Tokens from a `Pending` issuer are rejected because there are no keys to verify them with.
	Status *string `json:"status,omitempty"`
	// When the signing keys were last fetched. Absent while the issuer is `Pending`.
	JwksFetchedAt *time.Time `json:"jwksFetchedAt,omitempty"`
	// Creation timestamp.
	Created *time.Time `json:"created,omitempty"`
	// Last-update timestamp.
	Updated *time.Time `json:"updated,omitempty"`
}

// NewIssuer instantiates a new Issuer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuer() *Issuer {
	this := Issuer{}
	return &this
}

// NewIssuerWithDefaults instantiates a new Issuer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerWithDefaults() *Issuer {
	this := Issuer{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Issuer) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Issuer) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Issuer) SetId(v string) {
	o.Id = &v
}

// GetOrigin returns the Origin field value if set, zero value otherwise.
func (o *Issuer) GetOrigin() string {
	if o == nil || IsNil(o.Origin) {
		var ret string
		return ret
	}
	return *o.Origin
}

// GetOriginOk returns a tuple with the Origin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetOriginOk() (*string, bool) {
	if o == nil || IsNil(o.Origin) {
		return nil, false
	}
	return o.Origin, true
}

// HasOrigin returns a boolean if a field has been set.
func (o *Issuer) HasOrigin() bool {
	if o != nil && !IsNil(o.Origin) {
		return true
	}

	return false
}

// SetOrigin gets a reference to the given string and assigns it to the Origin field.
func (o *Issuer) SetOrigin(v string) {
	o.Origin = &v
}

// GetIssuerUrl returns the IssuerUrl field value if set, zero value otherwise.
func (o *Issuer) GetIssuerUrl() string {
	if o == nil || IsNil(o.IssuerUrl) {
		var ret string
		return ret
	}
	return *o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetIssuerUrlOk() (*string, bool) {
	if o == nil || IsNil(o.IssuerUrl) {
		return nil, false
	}
	return o.IssuerUrl, true
}

// HasIssuerUrl returns a boolean if a field has been set.
func (o *Issuer) HasIssuerUrl() bool {
	if o != nil && !IsNil(o.IssuerUrl) {
		return true
	}

	return false
}

// SetIssuerUrl gets a reference to the given string and assigns it to the IssuerUrl field.
func (o *Issuer) SetIssuerUrl(v string) {
	o.IssuerUrl = &v
}

// GetJwksUrl returns the JwksUrl field value if set, zero value otherwise.
func (o *Issuer) GetJwksUrl() string {
	if o == nil || IsNil(o.JwksUrl) {
		var ret string
		return ret
	}
	return *o.JwksUrl
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetJwksUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JwksUrl) {
		return nil, false
	}
	return o.JwksUrl, true
}

// HasJwksUrl returns a boolean if a field has been set.
func (o *Issuer) HasJwksUrl() bool {
	if o != nil && !IsNil(o.JwksUrl) {
		return true
	}

	return false
}

// SetJwksUrl gets a reference to the given string and assigns it to the JwksUrl field.
func (o *Issuer) SetJwksUrl(v string) {
	o.JwksUrl = &v
}

// GetJwksTimeout returns the JwksTimeout field value if set, zero value otherwise.
func (o *Issuer) GetJwksTimeout() string {
	if o == nil || IsNil(o.JwksTimeout) {
		var ret string
		return ret
	}
	return *o.JwksTimeout
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetJwksTimeoutOk() (*string, bool) {
	if o == nil || IsNil(o.JwksTimeout) {
		return nil, false
	}
	return o.JwksTimeout, true
}

// HasJwksTimeout returns a boolean if a field has been set.
func (o *Issuer) HasJwksTimeout() bool {
	if o != nil && !IsNil(o.JwksTimeout) {
		return true
	}

	return false
}

// SetJwksTimeout gets a reference to the given string and assigns it to the JwksTimeout field.
func (o *Issuer) SetJwksTimeout(v string) {
	o.JwksTimeout = &v
}

// GetServiceAccount returns the ServiceAccount field value if set, zero value otherwise.
func (o *Issuer) GetServiceAccount() bool {
	if o == nil || IsNil(o.ServiceAccount) {
		var ret bool
		return ret
	}
	return *o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.ServiceAccount) {
		return nil, false
	}
	return o.ServiceAccount, true
}

// HasServiceAccount returns a boolean if a field has been set.
func (o *Issuer) HasServiceAccount() bool {
	if o != nil && !IsNil(o.ServiceAccount) {
		return true
	}

	return false
}

// SetServiceAccount gets a reference to the given bool and assigns it to the ServiceAccount field.
func (o *Issuer) SetServiceAccount(v bool) {
	o.ServiceAccount = &v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *Issuer) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *Issuer) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *Issuer) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *Issuer) GetScopes() []string {
	if o == nil || IsNil(o.Scopes) {
		var ret []string
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetScopesOk() ([]string, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *Issuer) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []string and assigns it to the Scopes field.
func (o *Issuer) SetScopes(v []string) {
	o.Scopes = v
}

// GetClaimMappings returns the ClaimMappings field value if set, zero value otherwise.
func (o *Issuer) GetClaimMappings() []IssuerClaimMapping {
	if o == nil || IsNil(o.ClaimMappings) {
		var ret []IssuerClaimMapping
		return ret
	}
	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetClaimMappingsOk() ([]IssuerClaimMapping, bool) {
	if o == nil || IsNil(o.ClaimMappings) {
		return nil, false
	}
	return o.ClaimMappings, true
}

// HasClaimMappings returns a boolean if a field has been set.
func (o *Issuer) HasClaimMappings() bool {
	if o != nil && !IsNil(o.ClaimMappings) {
		return true
	}

	return false
}

// SetClaimMappings gets a reference to the given []IssuerClaimMapping and assigns it to the ClaimMappings field.
func (o *Issuer) SetClaimMappings(v []IssuerClaimMapping) {
	o.ClaimMappings = v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *Issuer) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *Issuer) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *Issuer) SetStatus(v string) {
	o.Status = &v
}

// GetJwksFetchedAt returns the JwksFetchedAt field value if set, zero value otherwise.
func (o *Issuer) GetJwksFetchedAt() time.Time {
	if o == nil || IsNil(o.JwksFetchedAt) {
		var ret time.Time
		return ret
	}
	return *o.JwksFetchedAt
}

// GetJwksFetchedAtOk returns a tuple with the JwksFetchedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetJwksFetchedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.JwksFetchedAt) {
		return nil, false
	}
	return o.JwksFetchedAt, true
}

// HasJwksFetchedAt returns a boolean if a field has been set.
func (o *Issuer) HasJwksFetchedAt() bool {
	if o != nil && !IsNil(o.JwksFetchedAt) {
		return true
	}

	return false
}

// SetJwksFetchedAt gets a reference to the given time.Time and assigns it to the JwksFetchedAt field.
func (o *Issuer) SetJwksFetchedAt(v time.Time) {
	o.JwksFetchedAt = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Issuer) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Issuer) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *Issuer) SetCreated(v time.Time) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *Issuer) GetUpdated() time.Time {
	if o == nil || IsNil(o.Updated) {
		var ret time.Time
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Issuer) GetUpdatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Updated) {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *Issuer) HasUpdated() bool {
	if o != nil && !IsNil(o.Updated) {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given time.Time and assigns it to the Updated field.
func (o *Issuer) SetUpdated(v time.Time) {
	o.Updated = &v
}

func (o Issuer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Issuer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Origin) {
		toSerialize["origin"] = o.Origin
	}
	if !IsNil(o.IssuerUrl) {
		toSerialize["issuerUrl"] = o.IssuerUrl
	}
	if !IsNil(o.JwksUrl) {
		toSerialize["jwksUrl"] = o.JwksUrl
	}
	if !IsNil(o.JwksTimeout) {
		toSerialize["jwksTimeout"] = o.JwksTimeout
	}
	if !IsNil(o.ServiceAccount) {
		toSerialize["serviceAccount"] = o.ServiceAccount
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	if !IsNil(o.ClaimMappings) {
		toSerialize["claimMappings"] = o.ClaimMappings
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.JwksFetchedAt) {
		toSerialize["jwksFetchedAt"] = o.JwksFetchedAt
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Updated) {
		toSerialize["updated"] = o.Updated
	}
	return toSerialize, nil
}

type NullableIssuer struct {
	value *Issuer
	isSet bool
}

func (v NullableIssuer) Get() *Issuer {
	return v.value
}

func (v *NullableIssuer) Set(val *Issuer) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuer) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuer(val *Issuer) *NullableIssuer {
	return &NullableIssuer{value: val, isSet: true}
}

func (v NullableIssuer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
