// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AuthIssuerClaimMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthIssuerClaimMapping{}

// AuthIssuerClaimMapping One entry in an Auth Issuer's claim mapping array.  Via the API, only `orgName` (required), `roles` (optional static list), and `isServiceAccount` (disconnected mode only) may be set. Attribute-driven fields (`orgAttribute`, `orgDisplayAttribute`, `rolesAttribute`) are reserved for ConfigMap-defined issuers and will be rejected with `400` if supplied.  An org name may be mapped at most once per issuer, and by default at most once across all issuers (both ConfigMap and API-created). Deployments that set `auth.sharedStaticOrgs` let several issuers map the same org with different roles; the name stays reserved either way, so no attribute-driven mapping can claim it. At most one `isServiceAccount: true` mapping may exist per org across all issuers, whether or not org names are shared.
type AuthIssuerClaimMapping struct {
	// Dynamic org claim path. Rejected for API-created issuers.
	OrgAttribute *string `json:"orgAttribute,omitempty"`
	// Dynamic org-display claim path. Rejected for API-created issuers.
	OrgDisplayAttribute *string `json:"orgDisplayAttribute,omitempty"`
	// Fixed org name for this mapping (required for API-created issuers). Unique across all issuers unless the deployment sets `auth.sharedStaticOrgs`.
	OrgName string `json:"orgName"`
	// Display name for the org.
	OrgDisplayName *string `json:"orgDisplayName,omitempty"`
	// Static role list. Omit when `isServiceAccount` is true (auto-assigns PROVIDER_ADMIN + TENANT_ADMIN).
	Roles []string `json:"roles,omitempty"`
	// Dynamic roles claim path. Rejected for API-created issuers.
	RolesAttribute *string `json:"rolesAttribute,omitempty"`
	// Optional per-mapping audience filter.
	Audiences []string `json:"audiences,omitempty"`
	// When true, auto-assigns PROVIDER_ADMIN and TENANT_ADMIN roles (disconnected mode only). Cannot be combined with `roles`, `rolesAttribute`, or `orgAttribute`. At most one service-account mapping is permitted per org across all issuers.
	IsServiceAccount *bool `json:"isServiceAccount,omitempty"`
}

type _AuthIssuerClaimMapping AuthIssuerClaimMapping

// NewAuthIssuerClaimMapping instantiates a new AuthIssuerClaimMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthIssuerClaimMapping(orgName string) *AuthIssuerClaimMapping {
	this := AuthIssuerClaimMapping{}
	this.OrgName = orgName
	return &this
}

// NewAuthIssuerClaimMappingWithDefaults instantiates a new AuthIssuerClaimMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthIssuerClaimMappingWithDefaults() *AuthIssuerClaimMapping {
	this := AuthIssuerClaimMapping{}
	return &this
}

// GetOrgAttribute returns the OrgAttribute field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetOrgAttribute() string {
	if o == nil || IsNil(o.OrgAttribute) {
		var ret string
		return ret
	}
	return *o.OrgAttribute
}

// GetOrgAttributeOk returns a tuple with the OrgAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetOrgAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.OrgAttribute) {
		return nil, false
	}
	return o.OrgAttribute, true
}

// HasOrgAttribute returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasOrgAttribute() bool {
	if o != nil && !IsNil(o.OrgAttribute) {
		return true
	}

	return false
}

// SetOrgAttribute gets a reference to the given string and assigns it to the OrgAttribute field.
func (o *AuthIssuerClaimMapping) SetOrgAttribute(v string) {
	o.OrgAttribute = &v
}

// GetOrgDisplayAttribute returns the OrgDisplayAttribute field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetOrgDisplayAttribute() string {
	if o == nil || IsNil(o.OrgDisplayAttribute) {
		var ret string
		return ret
	}
	return *o.OrgDisplayAttribute
}

// GetOrgDisplayAttributeOk returns a tuple with the OrgDisplayAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetOrgDisplayAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDisplayAttribute) {
		return nil, false
	}
	return o.OrgDisplayAttribute, true
}

// HasOrgDisplayAttribute returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasOrgDisplayAttribute() bool {
	if o != nil && !IsNil(o.OrgDisplayAttribute) {
		return true
	}

	return false
}

// SetOrgDisplayAttribute gets a reference to the given string and assigns it to the OrgDisplayAttribute field.
func (o *AuthIssuerClaimMapping) SetOrgDisplayAttribute(v string) {
	o.OrgDisplayAttribute = &v
}

// GetOrgName returns the OrgName field value
func (o *AuthIssuerClaimMapping) GetOrgName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetOrgNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgName, true
}

// SetOrgName sets field value
func (o *AuthIssuerClaimMapping) SetOrgName(v string) {
	o.OrgName = v
}

// GetOrgDisplayName returns the OrgDisplayName field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetOrgDisplayName() string {
	if o == nil || IsNil(o.OrgDisplayName) {
		var ret string
		return ret
	}
	return *o.OrgDisplayName
}

// GetOrgDisplayNameOk returns a tuple with the OrgDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetOrgDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDisplayName) {
		return nil, false
	}
	return o.OrgDisplayName, true
}

// HasOrgDisplayName returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasOrgDisplayName() bool {
	if o != nil && !IsNil(o.OrgDisplayName) {
		return true
	}

	return false
}

// SetOrgDisplayName gets a reference to the given string and assigns it to the OrgDisplayName field.
func (o *AuthIssuerClaimMapping) SetOrgDisplayName(v string) {
	o.OrgDisplayName = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *AuthIssuerClaimMapping) SetRoles(v []string) {
	o.Roles = v
}

// GetRolesAttribute returns the RolesAttribute field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetRolesAttribute() string {
	if o == nil || IsNil(o.RolesAttribute) {
		var ret string
		return ret
	}
	return *o.RolesAttribute
}

// GetRolesAttributeOk returns a tuple with the RolesAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetRolesAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.RolesAttribute) {
		return nil, false
	}
	return o.RolesAttribute, true
}

// HasRolesAttribute returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasRolesAttribute() bool {
	if o != nil && !IsNil(o.RolesAttribute) {
		return true
	}

	return false
}

// SetRolesAttribute gets a reference to the given string and assigns it to the RolesAttribute field.
func (o *AuthIssuerClaimMapping) SetRolesAttribute(v string) {
	o.RolesAttribute = &v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *AuthIssuerClaimMapping) SetAudiences(v []string) {
	o.Audiences = v
}

// GetIsServiceAccount returns the IsServiceAccount field value if set, zero value otherwise.
func (o *AuthIssuerClaimMapping) GetIsServiceAccount() bool {
	if o == nil || IsNil(o.IsServiceAccount) {
		var ret bool
		return ret
	}
	return *o.IsServiceAccount
}

// GetIsServiceAccountOk returns a tuple with the IsServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthIssuerClaimMapping) GetIsServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.IsServiceAccount) {
		return nil, false
	}
	return o.IsServiceAccount, true
}

// HasIsServiceAccount returns a boolean if a field has been set.
func (o *AuthIssuerClaimMapping) HasIsServiceAccount() bool {
	if o != nil && !IsNil(o.IsServiceAccount) {
		return true
	}

	return false
}

// SetIsServiceAccount gets a reference to the given bool and assigns it to the IsServiceAccount field.
func (o *AuthIssuerClaimMapping) SetIsServiceAccount(v bool) {
	o.IsServiceAccount = &v
}

func (o AuthIssuerClaimMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthIssuerClaimMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgAttribute) {
		toSerialize["orgAttribute"] = o.OrgAttribute
	}
	if !IsNil(o.OrgDisplayAttribute) {
		toSerialize["orgDisplayAttribute"] = o.OrgDisplayAttribute
	}
	toSerialize["orgName"] = o.OrgName
	if !IsNil(o.OrgDisplayName) {
		toSerialize["orgDisplayName"] = o.OrgDisplayName
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.RolesAttribute) {
		toSerialize["rolesAttribute"] = o.RolesAttribute
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.IsServiceAccount) {
		toSerialize["isServiceAccount"] = o.IsServiceAccount
	}
	return toSerialize, nil
}

func (o *AuthIssuerClaimMapping) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"orgName",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthIssuerClaimMapping := _AuthIssuerClaimMapping{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthIssuerClaimMapping)

	if err != nil {
		return err
	}

	*o = AuthIssuerClaimMapping(varAuthIssuerClaimMapping)

	return err
}

type NullableAuthIssuerClaimMapping struct {
	value *AuthIssuerClaimMapping
	isSet bool
}

func (v NullableAuthIssuerClaimMapping) Get() *AuthIssuerClaimMapping {
	return v.value
}

func (v *NullableAuthIssuerClaimMapping) Set(val *AuthIssuerClaimMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthIssuerClaimMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthIssuerClaimMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthIssuerClaimMapping(val *AuthIssuerClaimMapping) *NullableAuthIssuerClaimMapping {
	return &NullableAuthIssuerClaimMapping{value: val, isSet: true}
}

func (v NullableAuthIssuerClaimMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthIssuerClaimMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
