// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"encoding/json"
)

// checks if the IssuerClaimMapping type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IssuerClaimMapping{}

// IssuerClaimMapping One entry in an issuer's claim mapping array.  Via the API, only `orgName` (required), `roles` (optional static list), and `isServiceAccount` (disconnected mode only) may be set. Attribute-driven fields (`orgAttribute`, `orgDisplayAttribute`, `rolesAttribute`) are reserved for ConfigMap-defined issuers and will be rejected with `400` if supplied.  An org name may be mapped at most once per issuer, and by default at most once across all issuers (both ConfigMap and API-created). Deployments that set `auth.sharedStaticOrgs` let several issuers map the same org with different roles; the name stays reserved either way, so no attribute-driven mapping can claim it. At most one `isServiceAccount: true` mapping may exist per org across all issuers, whether or not org names are shared.
type IssuerClaimMapping struct {
	// Fixed org name for this mapping (required for API-created issuers). Unique across all issuers unless the deployment sets `auth.sharedStaticOrgs`.
	OrgName *string `json:"orgName,omitempty"`
	// Display name for the org.
	OrgDisplayName *string `json:"orgDisplayName,omitempty"`
	// Static role list. Omit when `isServiceAccount` is true (auto-assigns PROVIDER_ADMIN + TENANT_ADMIN).
	Roles []string `json:"roles,omitempty"`
	// Optional per-mapping audience filter.
	Audiences []string `json:"audiences,omitempty"`
	// When true, auto-assigns PROVIDER_ADMIN and TENANT_ADMIN roles (disconnected mode only). Cannot be combined with `roles`, `rolesAttribute`, or `orgAttribute`. At most one service-account mapping is permitted per org across all issuers.
	IsServiceAccount *bool `json:"isServiceAccount,omitempty"`
}

// NewIssuerClaimMapping instantiates a new IssuerClaimMapping object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIssuerClaimMapping() *IssuerClaimMapping {
	this := IssuerClaimMapping{}
	return &this
}

// NewIssuerClaimMappingWithDefaults instantiates a new IssuerClaimMapping object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIssuerClaimMappingWithDefaults() *IssuerClaimMapping {
	this := IssuerClaimMapping{}
	return &this
}

// GetOrgName returns the OrgName field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgName() string {
	if o == nil || IsNil(o.OrgName) {
		var ret string
		return ret
	}
	return *o.OrgName
}

// GetOrgNameOk returns a tuple with the OrgName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgName) {
		return nil, false
	}
	return o.OrgName, true
}

// HasOrgName returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgName() bool {
	if o != nil && !IsNil(o.OrgName) {
		return true
	}

	return false
}

// SetOrgName gets a reference to the given string and assigns it to the OrgName field.
func (o *IssuerClaimMapping) SetOrgName(v string) {
	o.OrgName = &v
}

// GetOrgDisplayName returns the OrgDisplayName field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetOrgDisplayName() string {
	if o == nil || IsNil(o.OrgDisplayName) {
		var ret string
		return ret
	}
	return *o.OrgDisplayName
}

// GetOrgDisplayNameOk returns a tuple with the OrgDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetOrgDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.OrgDisplayName) {
		return nil, false
	}
	return o.OrgDisplayName, true
}

// HasOrgDisplayName returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasOrgDisplayName() bool {
	if o != nil && !IsNil(o.OrgDisplayName) {
		return true
	}

	return false
}

// SetOrgDisplayName gets a reference to the given string and assigns it to the OrgDisplayName field.
func (o *IssuerClaimMapping) SetOrgDisplayName(v string) {
	o.OrgDisplayName = &v
}

// GetRoles returns the Roles field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetRoles() []string {
	if o == nil || IsNil(o.Roles) {
		var ret []string
		return ret
	}
	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetRolesOk() ([]string, bool) {
	if o == nil || IsNil(o.Roles) {
		return nil, false
	}
	return o.Roles, true
}

// HasRoles returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasRoles() bool {
	if o != nil && !IsNil(o.Roles) {
		return true
	}

	return false
}

// SetRoles gets a reference to the given []string and assigns it to the Roles field.
func (o *IssuerClaimMapping) SetRoles(v []string) {
	o.Roles = v
}

// GetAudiences returns the Audiences field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetAudiences() []string {
	if o == nil || IsNil(o.Audiences) {
		var ret []string
		return ret
	}
	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetAudiencesOk() ([]string, bool) {
	if o == nil || IsNil(o.Audiences) {
		return nil, false
	}
	return o.Audiences, true
}

// HasAudiences returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasAudiences() bool {
	if o != nil && !IsNil(o.Audiences) {
		return true
	}

	return false
}

// SetAudiences gets a reference to the given []string and assigns it to the Audiences field.
func (o *IssuerClaimMapping) SetAudiences(v []string) {
	o.Audiences = v
}

// GetIsServiceAccount returns the IsServiceAccount field value if set, zero value otherwise.
func (o *IssuerClaimMapping) GetIsServiceAccount() bool {
	if o == nil || IsNil(o.IsServiceAccount) {
		var ret bool
		return ret
	}
	return *o.IsServiceAccount
}

// GetIsServiceAccountOk returns a tuple with the IsServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IssuerClaimMapping) GetIsServiceAccountOk() (*bool, bool) {
	if o == nil || IsNil(o.IsServiceAccount) {
		return nil, false
	}
	return o.IsServiceAccount, true
}

// HasIsServiceAccount returns a boolean if a field has been set.
func (o *IssuerClaimMapping) HasIsServiceAccount() bool {
	if o != nil && !IsNil(o.IsServiceAccount) {
		return true
	}

	return false
}

// SetIsServiceAccount gets a reference to the given bool and assigns it to the IsServiceAccount field.
func (o *IssuerClaimMapping) SetIsServiceAccount(v bool) {
	o.IsServiceAccount = &v
}

func (o IssuerClaimMapping) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IssuerClaimMapping) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrgName) {
		toSerialize["orgName"] = o.OrgName
	}
	if !IsNil(o.OrgDisplayName) {
		toSerialize["orgDisplayName"] = o.OrgDisplayName
	}
	if !IsNil(o.Roles) {
		toSerialize["roles"] = o.Roles
	}
	if !IsNil(o.Audiences) {
		toSerialize["audiences"] = o.Audiences
	}
	if !IsNil(o.IsServiceAccount) {
		toSerialize["isServiceAccount"] = o.IsServiceAccount
	}
	return toSerialize, nil
}

type NullableIssuerClaimMapping struct {
	value *IssuerClaimMapping
	isSet bool
}

func (v NullableIssuerClaimMapping) Get() *IssuerClaimMapping {
	return v.value
}

func (v *NullableIssuerClaimMapping) Set(val *IssuerClaimMapping) {
	v.value = val
	v.isSet = true
}

func (v NullableIssuerClaimMapping) IsSet() bool {
	return v.isSet
}

func (v *NullableIssuerClaimMapping) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIssuerClaimMapping(val *IssuerClaimMapping) *NullableIssuerClaimMapping {
	return &NullableIssuerClaimMapping{value: val, isSet: true}
}

func (v NullableIssuerClaimMapping) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIssuerClaimMapping) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
