// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/*
NVIDIA Infra Controller REST API

NVIDIA Infra Controller REST API allows users to create and manage resources, e.g., VPCs, Subnets, and Instances, across all connected NVIDIA Infra Controller datacenters, also referred to as Sites.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package standard

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AuthIssuer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthIssuer{}

// AuthIssuer A runtime-managed external JWT Auth Issuer registered via the Provider Admin API.
type AuthIssuer struct {
	// Unique identifier of the issuer.
	Id string `json:"id"`
	// Token processor. Always `custom` for API-created issuers.
	Origin string `json:"origin"`
	// Expected JWT `iss` claim / OIDC issuer URL. Immutable after creation.
	IssuerUrl string `json:"issuerUrl"`
	// URL from which signing keys are fetched. Defaults to `{issuerUrl}/.well-known/jwks.json`.
	JwksUrl string `json:"jwksUrl"`
	// JWKS fetch timeout (Go duration string, e.g. `\"5s\"`).
	JwksTimeout string `json:"jwksTimeout"`
	// Enables client-credentials flow (disconnected mode only).
	ServiceAccount bool `json:"serviceAccount"`
	// Issuer-level allowed audience set; the token must carry at least one.
	Audiences []string `json:"audiences"`
	// Issuer-level required scope set; the token must carry all.
	Scopes []string `json:"scopes"`
	// Org/role mapping entries. Only static mappings (`orgName`) are permitted via the API.
	ClaimMappings []AuthIssuerClaimMapping `json:"claimMappings"`
	// Whether signing keys have been fetched from `jwksUrl`. Registration never contacts the identity provider, so an issuer starts `Pending` and becomes `Ready` once a background fetch succeeds. Tokens from a `Pending` issuer are rejected because there are no keys to verify them with.
	Status string `json:"status"`
	// When the signing keys were last fetched. Null while the issuer is `Pending`.
	JwksFetchedAt NullableTime `json:"jwksFetchedAt"`
	// Creation timestamp.
	Created time.Time `json:"created"`
	// Last-update timestamp.
	Updated time.Time `json:"updated"`
}

type _AuthIssuer AuthIssuer

// NewAuthIssuer instantiates a new AuthIssuer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthIssuer(id string, origin string, issuerUrl string, jwksUrl string, jwksTimeout string, serviceAccount bool, audiences []string, scopes []string, claimMappings []AuthIssuerClaimMapping, status string, jwksFetchedAt NullableTime, created time.Time, updated time.Time) *AuthIssuer {
	this := AuthIssuer{}
	this.Id = id
	this.Origin = origin
	this.IssuerUrl = issuerUrl
	this.JwksUrl = jwksUrl
	this.JwksTimeout = jwksTimeout
	this.ServiceAccount = serviceAccount
	this.Audiences = audiences
	this.Scopes = scopes
	this.ClaimMappings = claimMappings
	this.Status = status
	this.JwksFetchedAt = jwksFetchedAt
	this.Created = created
	this.Updated = updated
	return &this
}

// NewAuthIssuerWithDefaults instantiates a new AuthIssuer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthIssuerWithDefaults() *AuthIssuer {
	this := AuthIssuer{}
	return &this
}

// GetId returns the Id field value
func (o *AuthIssuer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AuthIssuer) SetId(v string) {
	o.Id = v
}

// GetOrigin returns the Origin field value
func (o *AuthIssuer) GetOrigin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Origin
}

// GetOriginOk returns a tuple with the Origin field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetOriginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Origin, true
}

// SetOrigin sets field value
func (o *AuthIssuer) SetOrigin(v string) {
	o.Origin = v
}

// GetIssuerUrl returns the IssuerUrl field value
func (o *AuthIssuer) GetIssuerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IssuerUrl
}

// GetIssuerUrlOk returns a tuple with the IssuerUrl field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetIssuerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IssuerUrl, true
}

// SetIssuerUrl sets field value
func (o *AuthIssuer) SetIssuerUrl(v string) {
	o.IssuerUrl = v
}

// GetJwksUrl returns the JwksUrl field value
func (o *AuthIssuer) GetJwksUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JwksUrl
}

// GetJwksUrlOk returns a tuple with the JwksUrl field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetJwksUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JwksUrl, true
}

// SetJwksUrl sets field value
func (o *AuthIssuer) SetJwksUrl(v string) {
	o.JwksUrl = v
}

// GetJwksTimeout returns the JwksTimeout field value
func (o *AuthIssuer) GetJwksTimeout() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JwksTimeout
}

// GetJwksTimeoutOk returns a tuple with the JwksTimeout field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetJwksTimeoutOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JwksTimeout, true
}

// SetJwksTimeout sets field value
func (o *AuthIssuer) SetJwksTimeout(v string) {
	o.JwksTimeout = v
}

// GetServiceAccount returns the ServiceAccount field value
func (o *AuthIssuer) GetServiceAccount() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetServiceAccountOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccount, true
}

// SetServiceAccount sets field value
func (o *AuthIssuer) SetServiceAccount(v bool) {
	o.ServiceAccount = v
}

// GetAudiences returns the Audiences field value
func (o *AuthIssuer) GetAudiences() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Audiences
}

// GetAudiencesOk returns a tuple with the Audiences field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetAudiencesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Audiences, true
}

// SetAudiences sets field value
func (o *AuthIssuer) SetAudiences(v []string) {
	o.Audiences = v
}

// GetScopes returns the Scopes field value
func (o *AuthIssuer) GetScopes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetScopesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scopes, true
}

// SetScopes sets field value
func (o *AuthIssuer) SetScopes(v []string) {
	o.Scopes = v
}

// GetClaimMappings returns the ClaimMappings field value
func (o *AuthIssuer) GetClaimMappings() []AuthIssuerClaimMapping {
	if o == nil {
		var ret []AuthIssuerClaimMapping
		return ret
	}

	return o.ClaimMappings
}

// GetClaimMappingsOk returns a tuple with the ClaimMappings field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetClaimMappingsOk() ([]AuthIssuerClaimMapping, bool) {
	if o == nil {
		return nil, false
	}
	return o.ClaimMappings, true
}

// SetClaimMappings sets field value
func (o *AuthIssuer) SetClaimMappings(v []AuthIssuerClaimMapping) {
	o.ClaimMappings = v
}

// GetStatus returns the Status field value
func (o *AuthIssuer) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *AuthIssuer) SetStatus(v string) {
	o.Status = v
}

// GetJwksFetchedAt returns the JwksFetchedAt field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *AuthIssuer) GetJwksFetchedAt() time.Time {
	if o == nil || o.JwksFetchedAt.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.JwksFetchedAt.Get()
}

// GetJwksFetchedAtOk returns a tuple with the JwksFetchedAt field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AuthIssuer) GetJwksFetchedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.JwksFetchedAt.Get(), o.JwksFetchedAt.IsSet()
}

// SetJwksFetchedAt sets field value
func (o *AuthIssuer) SetJwksFetchedAt(v time.Time) {
	o.JwksFetchedAt.Set(&v)
}

// GetCreated returns the Created field value
func (o *AuthIssuer) GetCreated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Created
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Created, true
}

// SetCreated sets field value
func (o *AuthIssuer) SetCreated(v time.Time) {
	o.Created = v
}

// GetUpdated returns the Updated field value
func (o *AuthIssuer) GetUpdated() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *AuthIssuer) GetUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *AuthIssuer) SetUpdated(v time.Time) {
	o.Updated = v
}

func (o AuthIssuer) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthIssuer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["origin"] = o.Origin
	toSerialize["issuerUrl"] = o.IssuerUrl
	toSerialize["jwksUrl"] = o.JwksUrl
	toSerialize["jwksTimeout"] = o.JwksTimeout
	toSerialize["serviceAccount"] = o.ServiceAccount
	toSerialize["audiences"] = o.Audiences
	toSerialize["scopes"] = o.Scopes
	toSerialize["claimMappings"] = o.ClaimMappings
	toSerialize["status"] = o.Status
	toSerialize["jwksFetchedAt"] = o.JwksFetchedAt.Get()
	toSerialize["created"] = o.Created
	toSerialize["updated"] = o.Updated
	return toSerialize, nil
}

func (o *AuthIssuer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"origin",
		"issuerUrl",
		"jwksUrl",
		"jwksTimeout",
		"serviceAccount",
		"audiences",
		"scopes",
		"claimMappings",
		"status",
		"jwksFetchedAt",
		"created",
		"updated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if value, exists := allProperties[requiredProperty]; !exists || value == nil {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthIssuer := _AuthIssuer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthIssuer)

	if err != nil {
		return err
	}

	*o = AuthIssuer(varAuthIssuer)

	return err
}

type NullableAuthIssuer struct {
	value *AuthIssuer
	isSet bool
}

func (v NullableAuthIssuer) Get() *AuthIssuer {
	return v.value
}

func (v *NullableAuthIssuer) Set(val *AuthIssuer) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthIssuer) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthIssuer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthIssuer(val *AuthIssuer) *NullableAuthIssuer {
	return &NullableAuthIssuer{value: val, isSet: true}
}

func (v NullableAuthIssuer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthIssuer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
