# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG CONTAINER_RUNTIME_X86_64

FROM $CONTAINER_RUNTIME_X86_64
# TODO replace this base container with GPU based containers

WORKDIR /
COPY crates/machine-validation/scripts /machine-validation/scripts

