# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

ARG CONTAINER_RUNTIME_X86_64

FROM $CONTAINER_RUNTIME_X86_64

WORKDIR /
COPY pxe/static/blobs/internal/ /

CMD exec /bin/sh -c "trap : TERM INT; sleep 9999999999d & wait"
